### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [Ashok-Varma/Gander#1]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by Ashok-Varma** [comment]
Hi @jbeguna04 ,

Thanks for the help. Just to give you an idea about the library. This helps developers to intercept all the calls made by app to server (Response from server, request from mobile). So they can check for issues in API's ..etc.

and then the name Gander. [Gander dictionary meaning](http://www.dictionary.com/browse/take-a-gander-at)
> Look at, glance at, as in Will you take a gander at that woman's red hair! This slangy idiom, dating from the early 1900s, presumably came from the verb gander, meaning “stretch one's neck to see,” possibly alluding to the long neck of the male goose.

**Comment by jbeguna04** [comment]
Thank you for the information sir. I will be applying those information in the logo.

**Comment by jbeguna04** [comment]
o

**Comment by jbeguna04** [comment]
Hello @Ashok-Varma , Thank you for waiting,
As I promised, here is my proposal for your logo/icon for your project Gander.

![ganddd](https://user-images.githubusercontent.com/35353768/43051230-4d9a9d40-8e49-11e8-9ff8-ad07ee3562ee.png)
If you have some suggestions about the design, feel free to open some. Thank you once again.

Best Reagrds,
-jbeguna04

**Comment by Ashok-Varma** [comment]
@jbeguna04  designs are great. especially the grey with orange beak is awesome.

1) For second icon the outline square color, can you add 2 more of those with different color outlines ?? i don't know which color looks good.
2) can you commit the PSD/SVG file also. 

 you can create a PR. thank you very much for the logo designs

**Comment by jbeguna04** [comment]
Hi @Ashok-Varma , Actually it is not the icon type for it. I will just present to you those and make choices of it. By the way thanks for your response about the logos.

**Comment by Ashok-Varma** [comment]
@jbeguna04 - Thanks for all the great design work.
You can create a PullRequest. and i want want to mention your work in library's home page. Can you send me following details
1. Display Name you want on page
2. Your Website Link or any other page that needs to be linked with your name.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/43059866-163d952c-8e81-11e8-978d-e412ee796ea0.png)

 Icon Variations. Feel free to choose icon variation above

**Comment by jbeguna04** [comment]
Jibbie Eguna(jbeguna04)
github.com/jbeguna04

**Comment by Ashok-Varma** [comment]
@jbeguna04 Thankyou for Awesome designs.

In readme.md you can use below syntax to show images. So it will be independent of other projects.
```
![Gander](LogoDesigns/logotype1.png)
```
Once again, great work man. these Logos are just awesome.

**Comment by Ashok-Varma** [comment]
@jbeguna04 one last help, can you also commit the one with white outline. Just with white outline around logo. just one icon is enough. 
grey, orange beak with white outline around it

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/43074955-ae582f86-8eb1-11e8-8f80-49417e3d42d2.png)
Whick specific color backgound do you prefer?

**Comment by Ashok-Varma** [comment]
i will add shadow and background later. I just need the icon with the white outline. 
I mean in above icons you specified everything expect the shadow and square.

**grey, orange beak with white outline around it**

>But since you asked, Out of these the first one looks very good and then the third one

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/43077010-c082a658-8eb8-11e8-8310-e32dd28829c6.png)
Is this what you meant?
sorry the white outline cant be seen but it has it

**Comment by Ashok-Varma** [comment]
@jbeguna04 - yeah just with that small white border/outline
Both SVG and PNG of this file.

Thankyou @jbeguna04

**Comment by jbeguna04** [comment]
Sure @Ashok-Varma , Give me couple of minutes :)

**Comment by jbeguna04** [comment]
Commited Icon Files :)

**Comment by Ashok-Varma** [comment]
@jbeguna04 Thanks a lot fot the help

**Comment by jbeguna04** [comment]
You are very welcome :)
