### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by lepicekmichal** [Ashok-Varma/Gander#11]
Is there migration to androidx planned? I would like to turn off jetifier and this is one of last libraries not to do the migration.

**Comment by justintuchek** [comment]
Hey 👋

I'm open to creating a pull request for this - if you're open to reviewing it then I'll get started 👍(more a question for maintainers, not sure on the state of the repo)

**Comment by emartynov** [comment]
I've created the pull request #14

**Comment by rr0055256** [comment]
Crashes in conjunction with Android X ? java.lang.IncompatibleClassChangeError: Class 'com.ashokvarma.gander.internal.ui.list.TransactionListActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData'

**Comment by emartynov** [comment]
Strange we don't have it here.

**Comment by Ashok-Varma** [comment]
Will verify this weekend and will try to merge The PR
