### ISSUE TITLE
Consider merging the project with Chucker?

### ISSUE THREAD

**Issue by ColtonIdle** [Ashok-Varma/Gander#15]
Chuck, Chucker and Gander are all great tools and projects, but it would seem beneficial to combine all of the efforts into a single repository.

Have you considered joining the https://github.com/ChuckerTeam/ so you can all put all your efforts towards a single project?

**Comment by Ashok-Varma** [comment]
I will join the team and can push the PR's to Chucker as well.
I fear Gander And Chucker have taken different paths it might be difficult to merge them
