### ISSUE TITLE
OkHttp 4

### ISSUE THREAD

**Issue by gotev** [Ashok-Varma/Gander#25]
Square recently released OkHttp 4. It's a Kotlin porting of OkHttp 3 with some minor changes and will be the basis of all the subsequent Square releases, so it's important to upgrade gander, as it currently crashes when used in an app with OkHttp 4. I can help with a PR but I preferred to write here first to let you know and have your feedback about it.

This is the stack trace:
```java
java.lang.NoSuchMethodError: No static method hasBody(Lokhttp3/Response;)Z in class Lokhttp3/internal/http/HttpHeaders; or its super classes
        at com.ashokvarma.gander.GanderInterceptor.updateTransactionFromResponse(GanderInterceptor.java:250)
        at com.ashokvarma.gander.GanderInterceptor.intercept(GanderInterceptor.java:161)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
```
And this is the official thread: https://github.com/square/okhttp/issues/5246 in which square devs advises to not rely on that method, but to copy and paste this one: https://github.com/square/okhttp/blob/eee838aebe8d3524d7e0e2dbf8f9bf357512f038/okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.kt#L213

**Comment by Ashok-Varma** [comment]
Sure @gotev. All PR's are welcome ?
Is it for OkHttp4 support or just fixing this issue ??

Also OkHttp4, many devs not yet moved because of minSdk and Java8 blockers. So may be i am thinking to maintain current version as well in separate branch just in case if someone needs this

**Comment by gotev** [comment]
With the proposed modifications gander will continue to work also with OkHttp 3.x. The only thing blocking OkHttp 4 is the above mentioned internal static method, which has been removed. My proposal is to make a static method which does the same stuff but inside gander, so it can be used with both OkHttp 3.x and 4.x. Haven't checked if you import other OkHttp internal packages. If so, I can help you get rid of them 😀

**Comment by Ashok-Varma** [comment]
sure @gotev you can create a PR for this

**Comment by gotev** [comment]
@Ashok-Varma made a check and it appears it was the only OkHttp internal method used 😉 

Just as advice, to ease other developers contributions consider adding CONTRIBUTING.md and CODE_OF_CONDUCT.md to your repo. This can be useful as an example: https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by gotev** [comment]
@ashok-varma any estimate on when this will be released? I could start using it right away when you're done

**Comment by Ashok-Varma** [comment]
@gotev already released yesterday. Not Updated in releases tab yet. You can use 3.1.0

**Comment by gotev** [comment]
Fantastic!!
