### ISSUE TITLE
Causing app to crash

### ISSUE THREAD

**Issue by tapandesai** [Ashok-Varma/Gander#32]
`Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'com.ashokvarma.gander.internal.ui.HttpTransactionUIHelper$Status com.ashokvarma.gander.internal.ui.HttpTransactionUIHelper.getStatus()' on a null object reference
com.ashokvarma.gander.internal.support.GanderColorUtil.getTransactionColor (GanderColorUtil.java:58)
com.ashokvarma.gander.internal.support.GanderColorUtil.getTransactionColor (GanderColorUtil.java:54)
com.ashokvarma.gander.internal.support.NotificationHelper.getNotificationText (NotificationHelper.java:113)
com.ashokvarma.gander.internal.support.NotificationHelper.show (NotificationHelper.java:95)
com.ashokvarma.gander.GanderInterceptor.create (GanderInterceptor.java:287)
com.ashokvarma.gander.GanderInterceptor.createTransactionFromRequest (GanderInterceptor.java:215)
com.ashokvarma.gander.GanderInterceptor.intercept (GanderInterceptor.java:154)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:45)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:127)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.careclues.physician.development.client.ApiClient.lambda$getClient$0 (ApiClient.java:55)
com.careclues.physician.development.client.-$$Lambda$ApiClient$0YUme7uifQFB3wmjrrftotg11_I.intercept (Unknown Source:4)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.java:225)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:257)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:201)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)`

**Comment by amitav13** [comment]
Any updates? Getting this as well.

**Comment by Ashok-Varma** [comment]
It's due to [migration](https://github.com/Ashok-Varma/Gander/releases/tag/3.0.0
) to new version. In new version we need to specify the storage option you need.

```
  @Override
    public void onCreate() {
        super.onCreate();
        // For Persistence (Uses Room to store the calls in DB)
        Gander.setGanderStorage(GanderPersistence.getInstance(this));
        // For In Memory DB (Data retained in memory lost on app close)
        Gander.setGanderStorage(GanderIMDB.getInstance());
    }
```
