### ISSUE TITLE
StackOverflowError in Release

### ISSUE THREAD

**Issue by kele89** [Ashok-Varma/Gander#39]
I'm getting a StackOverflowError in a release build where I have:

releaseImplementation 'com.ashokvarma.android:gander-no-op:3.1.0'

Should this happen?
Is Gander still active in the background in no-op builds?

Attaching a stack trace for reference.

[Gander_StackOverFlow_error.txt](https://github.com/Ashok-Varma/Gander/files/7667111/Gander_StackOverFlow_error.txt)

**Comment by Ashok-Varma** [comment]
Gander no-op will have empty interceptor.

You can check [NoOpInterceptor here](https://github.com/Ashok-Varma/Gander/blob/master/gander-no-op/src/main/java/com/ashokvarma/gander/GanderInterceptor.java)
