### ISSUE TITLE
Upload Error : StreamResetException

### ISSUE THREAD

**Issue by beingentangled** [Ashok-Varma/Gander#4]
okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

**Comment by Ashok-Varma** [comment]
@beingentangled Can you send the stack trace. This exception is not from this library.

You can check these links with similar issue. That might be helpful.
https://github.com/square/okhttp/issues/1897
https://github.com/square/okhttp/issues/1844
