### ISSUE TITLE
Proposal: No dismissable notification

### ISSUE THREAD

**Issue by alorma** [Ashok-Varma/Gander#7]
Hi.

Someone on my team says it could be a good addition to make the notification static, so it cannot be removed from the notifications tray.

Do you think is a good addition? I can open a pull request if you want

**Comment by Ashok-Varma** [comment]
Hi @alorma 

You can create a PR. But that should be as an option to Dev. If he prefers Sticky they can enable it else default behaviour.

**Comment by alorma** [comment]
yes, it was my intention, create the option to make it sticky or not (not by default)
