### ISSUE TITLE
Feature request: GraphQL implementation

### ISSUE THREAD

**Issue by rnitame** [Ashok-Varma/Gander#9]
I want to feature for GraphQL. 
All response code and title are same.（ref: image ↓

![image](https://user-images.githubusercontent.com/4950792/51022375-604f5d80-15c7-11e9-9c44-e2a209229c65.png)

Do you think is a good feature? I can open a pull request if you are ok.

**Comment by Ashok-Varma** [comment]
It works for GraphQL. Is this a sample ?

**Comment by Ashok-Varma** [comment]
@rnitame so any update in this ?

**Comment by Ashok-Varma** [comment]
because this
